"use client";

import { useState } from "react";

const warehouseInventory = [
  { location: "Los Angeles", code: "LA-01", units: "12,480", status: "Healthy", tone: "bg-emerald-100 text-emerald-700" },
  { location: "Zaragoza", code: "ZA-01", units: "8,260", status: "Review 4 SKUs", tone: "bg-amber-100 text-amber-700" },
];

const operations = [
  { label: "Orders awaiting pick", value: "184", detail: "Across both warehouses", icon: "↗" },
  { label: "In transit", value: "2,438", detail: "98.7% on-time delivery", icon: "◌" },
  { label: "Returns to review", value: "36", detail: "18–25% of volume by client", icon: "↩" },
];

export default function BackofficeHomePage() {
  const [activeSection, setActiveSection] = useState("Overview");

  return <div className="min-h-screen lg:flex">
    <aside className="bg-navy p-5 text-white lg:flex lg:min-h-screen lg:w-72 lg:flex-col lg:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-mint font-bold text-black">▦</span><div><p className="font-extrabold tracking-[0.12em]">TRACKFLOW</p><p className="text-xs text-white/50">Operations workspace</p></div></div><nav className="mt-10 flex gap-2 overflow-x-auto lg:block" aria-label="Operations navigation">{["Overview", "Inventory", "Shipments", "Returns"].map((item) => <button key={item} type="button" onClick={() => setActiveSection(item)} className={`focus-ring mb-2 whitespace-nowrap rounded-xl px-4 py-3 text-left text-sm font-semibold transition lg:block lg:w-full ${activeSection === item ? "bg-white/10 text-mint" : "text-white/60 hover:bg-white/5 hover:text-white"}`}>{item}</button>)}</nav><div className="mt-auto hidden rounded-2xl border border-white/10 bg-white/5 p-4 lg:block"><p className="text-xs uppercase tracking-widest text-white/40">System status</p><p className="mt-3 flex items-center gap-2 text-sm font-bold"><span className="h-2 w-2 rounded-full bg-mint" /> All systems operational</p><p className="mt-2 text-xs leading-5 text-white/50">Last synced from LA and Zaragoza 4 min ago.</p></div></aside>
    <main className="flex-1 p-5 sm:p-8 lg:p-12"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-sm font-bold text-slate-400">Monday, September 27, 2026</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">Good morning, TrackFlow team.</h1><p className="mt-3 max-w-2xl text-slate-500">A single view of the operation across Los Angeles and Zaragoza.</p></div><div className="flex items-center gap-3"><button type="button" className="focus-ring rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-600">Export report</button><div className="flex h-11 w-11 items-center justify-center rounded-full bg-navy font-bold text-white" aria-label="Signed in as Operations">OP</div></div></header>
      <section className="mt-10 grid gap-4 md:grid-cols-3" aria-label="Operations metrics">{operations.map((operation) => <article key={operation.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-sm font-semibold text-slate-500">{operation.label}</p><span className="text-lg text-mint">{operation.icon}</span></div><p className="mt-5 text-4xl font-extrabold tracking-tight">{operation.value}</p><p className="mt-2 text-xs text-slate-400">{operation.detail}</p></article>)}</section>
      <section className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold uppercase tracking-widest text-slate-400">Unified inventory</p><h2 className="mt-2 text-2xl font-extrabold">Warehouse snapshot</h2></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Live data preview</span></div><div className="mt-6 space-y-3">{warehouseInventory.map((warehouse) => <div key={warehouse.code} className="flex flex-col gap-3 rounded-xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{warehouse.location} <span className="ml-2 text-xs font-normal text-slate-400">{warehouse.code}</span></p><p className="mt-1 text-sm text-slate-500">Available inventory units</p></div><div className="flex items-center gap-4"><p className="text-xl font-extrabold">{warehouse.units}</p><span className={`rounded-full px-3 py-1 text-xs font-bold ${warehouse.tone}`}>{warehouse.status}</span></div></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-400">This operational preview reflects TrackFlow&apos;s two-country warehouse model. Connect the central inventory API to replace sample values.</p></article><aside className="rounded-2xl bg-navy p-6 text-white"><p className="text-xs font-extrabold uppercase tracking-widest text-mint">Team focus</p><h2 className="mt-3 text-2xl font-extrabold">{activeSection} workspace</h2><p className="mt-4 text-sm leading-6 text-white/60">Use this entry point to coordinate warehouse, last-mile, and returns workflows. Detailed permissions and live API connections are planned for the next milestone.</p><button type="button" className="focus-ring mt-8 rounded-xl bg-mint px-4 py-3 text-sm font-extrabold text-black">Open {activeSection.toLowerCase()} queue ↗</button></aside></section>
    </main>
  </div>;
}
